GET http://localhost:8080/products/

###

GET http://localhost:8080/products/single/106

###

GET http://localhost:8080/products/latest

###

GET http://localhost:8080/products/mostpopulars

###

POST http://localhost:8080/products/
Content-Type: application/json

{
  "name": "testproduct"
}